server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates: 
        - Path=/users/**
      
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates: 
        - Path=/hotels/** , /staffs/**
      
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates: 
        - Path=/ratings/**     

#this will make this user service as a client and register with service registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka