server:
  port: 9000

eureka:
  instance:
    hostname: localhost
# we will make it false so that it will not register with itself 
# because this is a server not a client
  client:
    register-with-eureka: false
    fetch-registry: false