server:
  port: 9081

spring: 
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 #used for config server
  config:
    import: optional:configserver:http://localhost:8085
    
#this will make this user service as a client and register with service registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
resilience4j:
 ratelimiter: 
  instances:
    ratingHotelLimiter:
      limit-refresh-period: 4s
      limit-for-period: 2
      timeout-duration: 2s
# retry:
#  instances:
#   ratingHotelCircuitBreaker:
#    max-attempts: 4
#    wait-duration: 5s
# circuitbreaker:
##  configs:
##        default:
##            registerHealthIndicator: true
#  instances: 
#   ratingHotelCircuitBreaker: 
#     registerHealthIndicator: true 
#     eventConsumerBufferSize: 10 
#     failureRateThreshold: 5 
#     minimumNumberOfCalls: 3 
#     automaticTransitionFromOpenToHalfOpenEnabled: true 
#     waitDurationInOpenState: 6s 
#     permittedNumberOfCallsInHalfOpenState: 3 
#     slidingWindowSize: 10 
#     slidingWindowType: COUNT_BASED
                    